<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251205093106 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE meal_products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, meal_id INT DEFAULT NULL, product_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D7A84128639666D6 ON meal_products (meal_id)');
        $this->addSql('CREATE INDEX IDX_D7A841284584665A ON meal_products (product_id)');
        $this->addSql('CREATE TABLE meals (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, calories INT NOT NULL, unit VARCHAR(255) NOT NULL, unit_amount INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE meal_products ADD CONSTRAINT FK_D7A84128639666D6 FOREIGN KEY (meal_id) REFERENCES meals (id)');
        $this->addSql('ALTER TABLE meal_products ADD CONSTRAINT FK_D7A841284584665A FOREIGN KEY (product_id) REFERENCES products (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE meal_products DROP CONSTRAINT FK_D7A84128639666D6');
        $this->addSql('ALTER TABLE meal_products DROP CONSTRAINT FK_D7A841284584665A');
        $this->addSql('DROP TABLE meal_products');
        $this->addSql('DROP TABLE meals');
        $this->addSql('DROP TABLE products');
    }
}
