<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251208103035 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE daily_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, max_calories INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE daily_log_meals (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, daily_log_id INT DEFAULT NULL, meal_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_435314AD6B596A2A ON daily_log_meals (daily_log_id)');
        $this->addSql('CREATE INDEX IDX_435314AD639666D6 ON daily_log_meals (meal_id)');
        $this->addSql('ALTER TABLE daily_log_meals ADD CONSTRAINT FK_435314AD6B596A2A FOREIGN KEY (daily_log_id) REFERENCES daily_log (id)');
        $this->addSql('ALTER TABLE daily_log_meals ADD CONSTRAINT FK_435314AD639666D6 FOREIGN KEY (meal_id) REFERENCES meals (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE daily_log_meals DROP CONSTRAINT FK_435314AD6B596A2A');
        $this->addSql('ALTER TABLE daily_log_meals DROP CONSTRAINT FK_435314AD639666D6');
        $this->addSql('DROP TABLE daily_log');
        $this->addSql('DROP TABLE daily_log_meals');
    }
}
